//@version=4

study("MJ - Conditional EMAs", overlay=true)

COLOR_LIME = #1cd206
COLOR_VOLT = #affd00
COLOR_PINK = #e63a97
COLOR_RED = #f21616
COLOR_LIGHT_BLUE = #3179f5
COLOR_MAGENTA = #d612f8
COLOR_ORANGE = #f57f17
COLOR_GOLD = #ffb74d

//////////////////////////////////////////////////////////////////
// 
// ==== CONDITIONAL EMAs ==== 
// 
//////////////////////////////////////////////////////////////////

groupMarkers = 'EMA Cross Markers'

ema5Color = input(color.new(#ffeb3b, 20), '5 EMA Color')
ema13Color = input(color.new(#b71c1c, 20), '13 EMA Color')
ema50Color = input(color.new(#00bcd4, 20), '50 EMA Color')
ema200Color = input(color.new(#ffffff, 20), '200 EMA Color')
ema800Color = input(color.new(#1848cc, 20), '800 EMA Color')
ema50CloudColor = input(color.new(#26c6da, 85), '50 EMA Cloud Color')
emaConditional1hColor = input(color.new(COLOR_ORANGE, 15), 'EMA Conditional 1h Color')
emaConditional15mColor = input(color.new(COLOR_MAGENTA, 40), 'EMA Conditional 15m Color')
emaConditional5mColor = input(color.new(COLOR_LIME, 40), 'EMA Conditional 5m Color')
emaConditional30mColor = input(color.new(COLOR_LIGHT_BLUE, 40), 'EMA Conditional 30m Color')
showConditionalEma1hLine = input(false, 'Show Conditional 1h line?')
showConditionalEma15mLine = input(false, 'Show Conditional 15m line?')
showConditionalEma5mLine = input(false, 'Show Conditional 5m line?')
showConditionalEma30mLine = input(false, 'Show Conditional 30m line?')
showConditionalEma1hLabel = input(true, 'Show Conditional 1h label?')
showConditionalEma15mLabel = input(true, 'Show Conditional 15m label?')
showConditionalEma5mLabel = input(true, 'Show Conditional 5m label?')
showConditionalEma30mLabel = input(true, 'Show Conditional 30m label?')

lineWidth = input(2, 'EMA Line Width', options=[1,2,3,4])
labelOffsetStandard = input(8, 'Standard EMA Label Offset (in bars)')
labelOffsetConditional = input(
     defval=16, 
     title='Conditional EMA Label Offset (in bars)', 
     tooltip='Only applicable when showLabelText is true.  If showLabelText is false, this will be set to labelOffsetStandard.')
labelOpacity = input(30, 'Label Opacity')
labelStyle = input(label.style_circle, 'Label Style', options=[label.style_none, label.style_label_up, label.style_label_upper_right, label.style_label_right, label.style_label_lower_right, label.style_label_down, label.style_label_lower_left, label.style_label_left, label.style_label_upper_left, label.style_label_center, label.style_triangleup, label.style_triangledown, label.style_arrowup, label.style_arrowdown, label.style_xcross, label.style_cross, label.style_flag, label.style_circle])
labelSize = input(size.auto, 'Label Size', options=[size.auto, size.tiny, size.small, size.normal, size.large])
showLabelText = input(false, 'Show Label Text?')

_getConditionalValues() => 
    if timeframe.period == '1'
        [3000, 750, 250, 1500]
    else if timeframe.period == '5'
        [600, 150, 0, 300]
    else if timeframe.period == '30'
        [100, 0, 0, 0]
    else 
        [0, 0, 0, 0]

_getConditionalLabels() => 
    if timeframe.period == '1'
        ['3000 => 50EMA on 1h', '750 => 50EMA on 15m', '250 => 50EMA on 5m', '1500 => 50EMA on 30m']
    else if timeframe.period == '5'
        ['600 => 50EMA on 1h', '150 => 50EMA on 15m', '', '1200 => 50EMA on 30m']
    else if timeframe.period == '30'
        ['100 => 50EMA on 1h', '', '', '']
    else 
        ['', '', '', '']

_getFutureTimeNBarsFromNow(numBars) => time + ( ( time - time[1] ) * numBars )

_drawLabel(y, text, Color, textColor, offset) => 
    x = _getFutureTimeNBarsFromNow(offset)

    if barstate.islast
        _color = color.new(Color, labelOpacity)
        _textColor = labelStyle == label.style_none ? color.new(Color, 0) : textColor // If no label style, use the same color as the line
        _text = showLabelText ? text : na
        y ? label.new(
             x=x, 
             y=y, 
             text=_text, 
             style=labelStyle, 
             textcolor=_textColor, 
             color=_color, 
             size=labelSize, 
             tooltip=text,
             xloc=xloc.bar_time) : na

// -----------------
// Get Values
// -----------------

_getEmaVal(length) => length > 0 ? ema(close, length) : na

ema5 = ema(close, 5)
ema13 = ema(close, 13)
ema50 = ema(close, 50)
ema200 = ema(close, 200)
ema800 = ema(close, 800)

[_1hVal, _15mVal, _5mVal, _30mVal] = _getConditionalValues()
emaConditional1h = _getEmaVal(_1hVal)
emaConditional15m = _getEmaVal(_15mVal)
emaConditional5m = _getEmaVal(_5mVal)
// emaConditional30m = _getEmaVal(_30mVal)

[emaConditional1hText, emaConditional15mText, emaConditional5mText, emaConditional30mText] = _getConditionalLabels()

// -----------------
// Plot EMAs
// -----------------

// standard EMAs

plot(ema5, color=ema5Color, linewidth=lineWidth, title="EMA 5")
plot(ema13, color=ema13Color, linewidth=lineWidth, title="EMA 13")
plot(ema50, color=ema50Color, linewidth=lineWidth, title="EMA 50")
plot(ema200, color=ema200Color, linewidth=lineWidth, title="EMA 200")
plot(ema800, color=ema800Color, linewidth=lineWidth, title="EMA 800")

// conditional EMAs

plot(
     showConditionalEma1hLine ? emaConditional1h : na, 
     color=emaConditional1hColor, 
     linewidth=lineWidth, 
     title='EMA Conditional 1h')

plot(showConditionalEma15mLine ? emaConditional15m : na, 
     color=emaConditional15mColor, 
     linewidth=lineWidth, 
     title='EMA Conditional 15m')

plot(showConditionalEma5mLine ? emaConditional5m : na, 
     color=emaConditional5mColor, 
     linewidth=lineWidth, 
     title='EMA Conditional 5m')

// plot(showConditionalEma30mLine ? emaConditional30m : na, 
//      color=emaConditional30mColor, 
//      linewidth=lineWidth, 
//      title='EMA Conditional 30m')

// ----------------------------
// Plot 50 EMA Cloud
// ----------------------------

cloudSize = stdev(close, 50 * 2) / 4 // 50 because it's for the 50 EMA
cloudPlotUpper = plot(ema50 + cloudSize, '50 EMA Upper Cloud', color=ema50CloudColor, offset=0)
cloudPlotLower = plot(ema50 - cloudSize, '50 EMA Lower Cloud', color=ema50CloudColor, offset=0)
fill(cloudPlotUpper, cloudPlotLower, title='50 EMA Cloud', color=ema50CloudColor)

// ---------------------------
// Draw Labels
// ---------------------------

// standard

label5 = _drawLabel(ema5, '5', ema5Color, color.white, labelOffsetStandard)
label13 = _drawLabel(ema13, '13', ema13Color, color.white, labelOffsetStandard)
label50 = _drawLabel(ema50, '50', ema50Color, color.white, labelOffsetStandard)
label200 = _drawLabel(ema200, '200', ema200Color, color.white, labelOffsetStandard)
label800 = _drawLabel(ema800, '800', ema800Color, color.white, labelOffsetStandard)

// conditional

_conditionalLabelOffset = showLabelText ? labelOffsetConditional : labelOffsetStandard

labelConditional1h = _drawLabel(
     showConditionalEma1hLabel ? emaConditional1h : na, 
     emaConditional1hText, 
     emaConditional1hColor, 
     color.white, 
     _conditionalLabelOffset)

labelConditional15m = _drawLabel(
     showConditionalEma15mLabel ? emaConditional15m : na, 
     emaConditional15mText, 
     emaConditional15mColor, 
     color.white, 
     _conditionalLabelOffset)

labelConditional5m = _drawLabel(
     showConditionalEma5mLabel ? emaConditional5m : na, 
     emaConditional5mText, 
     emaConditional5mColor, 
     color.white, 
     _conditionalLabelOffset)

// labelConditional30m = _drawLabel(
//      showConditionalEma30mLabel ? emaConditional30m : na, 
//      emaConditional30mText, 
//      emaConditional30mColor, 
//      color.white, 
//      _conditionalLabelOffset)

label.delete(label5[1])
label.delete(label13[1])
label.delete(label50[1])
label.delete(label200[1])
label.delete(label800[1])
label.delete(labelConditional1h[1])
label.delete(labelConditional15m[1])
label.delete(labelConditional5m[1])
// label.delete(labelConditional30m[1])

// -----------------
// Cross Markers
// -----------------
// Active
allMarkersActive = input(true, 'Markers Active?', group=groupMarkers)
marker5x13Active = input(false, 'Plot 5/13 Cross?', group=groupMarkers)
marker5x50Active = input(false, 'Plot 5/50 Cross?', group=groupMarkers)
marker13x50Active = input(true, 'Plot 13/50 Cross?', group=groupMarkers)
marker13x200Active = input(false, 'Plot 13/200 Cross?', group=groupMarkers)
marker50x200Active = input(true, 'Plot 50/200 Cross?', group=groupMarkers)
marker50x800Active = input(true, 'Plot 50/800 Cross?', group=groupMarkers)
marker200x800Active = input(true, 'Plot 200/800 Cross?', group=groupMarkers)
// Color
markerTextColorSameAsMarker = input(false, 'Text Color Same as Marker?', group=groupMarkers)
markerTextColorDefault = input(color.new(color.white, 0), 'Text Color Default', group=groupMarkers)
markerCrossUpColor = input(color.new(COLOR_LIGHT_BLUE, 0), 'Cross Up Color', group=groupMarkers)
markerCrossDownColor = input(color.new(COLOR_MAGENTA, 0), 'Cross Down Color', group=groupMarkers)
// Opacity
shapeOpacity5x13 = input(70, 'Shape Opacity 5x13', minval=0, maxval=100, group=groupMarkers)
shapeOpacity5x50 = input(70, 'Shape Opacity 5x50', minval=0, maxval=100, group=groupMarkers)
shapeOpacity13x50 = input(0, 'Shape Opacity 13x50', minval=0, maxval=100, group=groupMarkers)
shapeOpacity13x200 = input(40, 'Shape Opacity 13x200', minval=0, maxval=100, group=groupMarkers)
shapeOpacity50x200 = input(0, 'Shape Opacity 50x200', minval=0, maxval=100, group=groupMarkers)
shapeOpacity50x800 = input(20, 'Shape Opacity 50x800', minval=0, maxval=100, group=groupMarkers)
shapeOpacity200x800 = input(20, 'Shape Opacity 200x800', minval=0, maxval=100, group=groupMarkers)
textOpacity5x13 = input(20, 'Text Opacity 5x13', minval=0, maxval=100, group=groupMarkers)
textOpacity5x50 = input(20, 'Text Opacity 5x50', minval=0, maxval=100, group=groupMarkers)
textOpacity13x50 = input(0, 'Text Opacity 13x50', minval=0, maxval=100, group=groupMarkers)
textOpacity13x200 = input(10, 'Text Opacity 13x200', minval=0, maxval=100, group=groupMarkers)
textOpacity50x200 = input(0, 'Text Opacity 50x200', minval=0, maxval=100, group=groupMarkers)
textOpacity50x800 = input(10, 'Text Opacity 50x800', minval=0, maxval=100, group=groupMarkers)
textOpacity200x800 = input(10, 'Text Opacity 200x800', minval=0, maxval=100, group=groupMarkers)

upTextColor = markerTextColorSameAsMarker ? markerCrossUpColor : markerTextColorDefault
downTextColor = markerTextColorSameAsMarker ? markerCrossDownColor : markerTextColorDefault

_getEmaCrossMarkerVisibility(emaOne, emaTwo, markerActive) => 
    didCrossUp = crossover(emaOne, emaTwo)
    didCrossDown = crossunder(emaOne, emaTwo)
    showUpMarker = didCrossUp and markerActive and allMarkersActive
    showDownMarker = didCrossDown and markerActive and allMarkersActive
    [showUpMarker, showDownMarker]

// =====================================
// MARKERS USING PLOTSHAPE
// =====================================

markerCrossUpPlotStyle = input(shape.triangleup, 'Shape Style Up', options=[shape.xcross, shape.cross, shape.triangleup, shape.triangledown, shape.flag, shape.circle, shape.arrowup, shape.arrowdown, shape.labelup, shape.labeldown, shape.square, shape.diamond], group=groupMarkers)
markerCrossDownPlotStyle = input(shape.triangledown, 'Shape Style Down', options=[shape.xcross, shape.cross, shape.triangleup, shape.triangledown, shape.flag, shape.circle, shape.arrowup, shape.arrowdown, shape.labelup, shape.labeldown, shape.square, shape.diamond], group=groupMarkers)
markerCrossUpPlotLocation = input(location.bottom, 'Shape Location Up', options=[location.abovebar, location.belowbar, location.top, location.bottom, location.absolute], group=groupMarkers)
markerCrossDownPlotLocation = input(location.top, 'Shape Location Down', options=[location.abovebar, location.belowbar, location.top, location.bottom, location.absolute], group=groupMarkers)
markerShapeSize = size.small

[isVisible5x13Up, isVisible5x13Down] = _getEmaCrossMarkerVisibility(ema5, ema13, marker5x13Active)
[isVisible5x50Up, isVisible5x50Down] = _getEmaCrossMarkerVisibility(ema5, ema50, marker5x50Active)
[isVisible13x50Up, isVisible13x50Down] = _getEmaCrossMarkerVisibility(ema13, ema50, marker13x50Active)
[isVisible13x200Up, isVisible13x200Down] = _getEmaCrossMarkerVisibility(ema13, ema200, marker13x200Active)
[isVisible50x200Up, isVisible50x200Down] = _getEmaCrossMarkerVisibility(ema50, ema200, marker50x200Active)
[isVisible50x800Up, isVisible50x800Down] = _getEmaCrossMarkerVisibility(ema50, ema800, marker50x800Active)
[isVisible200x800Up, isVisible200x800Down] = _getEmaCrossMarkerVisibility(ema200, ema800, marker200x800Active)

// ----------------------
// 5x13
// ----------------------

plotshape(
     series=isVisible5x13Up, 
     text='5x13',
     title='5x13Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity5x13),
     textcolor=color.new(upTextColor, textOpacity5x13),
     size=markerShapeSize)

plotshape(
     series=isVisible5x13Down, 
     text='5x13',
     title='5x13Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity5x13),
     textcolor=color.new(downTextColor, textOpacity5x13),
     size=markerShapeSize)

// ----------------------
// 5x50
// ----------------------

plotshape(
     series=isVisible5x50Up, 
     text='5x50',
     title='5x50Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity5x50),
     textcolor=color.new(upTextColor, textOpacity5x50),
     size=markerShapeSize)

plotshape(
     series=isVisible5x50Down, 
     text='5x50',
     title='5x50Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity5x50),
     textcolor=color.new(downTextColor, textOpacity5x50),
     size=markerShapeSize)

// ----------------------
// 13x50
// ----------------------

plotshape(
     series=isVisible13x50Up, 
     text='13x50',
     title='13x50Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity13x50),
     textcolor=color.new(upTextColor, textOpacity13x50),
     size=markerShapeSize)

plotshape(
     series=isVisible13x50Down, 
     text='13x50',
     title='13x50Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity13x50),
     textcolor=color.new(downTextColor, textOpacity13x50),
     size=markerShapeSize)

// ----------------------
// 13x200
// ----------------------

plotshape(
     series=isVisible13x200Up, 
     text='13x200',
     title='13x200Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity13x200),
     textcolor=color.new(upTextColor, textOpacity13x200),
     size=markerShapeSize)

plotshape(
     series=isVisible13x200Down, 
     text='13x200',
     title='13x200Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity13x200),
     textcolor=color.new(downTextColor, textOpacity13x200),
     size=markerShapeSize)

// ----------------------
// 50x200
// ----------------------

plotshape(
     series=isVisible50x200Up, 
     text='50x200',
     title='50x200Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity50x200),
     textcolor=color.new(upTextColor, textOpacity50x200),
     size=markerShapeSize)

plotshape(
     series=isVisible50x200Down, 
     text='50x200',
     title='50x200Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity50x200),
     textcolor=color.new(downTextColor, textOpacity50x200),
     size=markerShapeSize)

// ----------------------
// 50x800
// ----------------------

plotshape(
     series=isVisible50x800Up, 
     text='50x800',
     title='50x800Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity50x800),
     textcolor=color.new(upTextColor, textOpacity50x800),
     size=markerShapeSize)

plotshape(
     series=isVisible50x800Down, 
     text='50x800',
     title='50x800Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity50x800),
     textcolor=color.new(downTextColor, textOpacity50x800),
     size=markerShapeSize)

// ----------------------
// 200x800
// ----------------------

plotshape(
     series=isVisible200x800Up, 
     text='200x800',
     title='200x800Up', 
     style=markerCrossUpPlotStyle, 
     location=markerCrossUpPlotLocation, 
     color=color.new(markerCrossUpColor, shapeOpacity200x800),
     textcolor=color.new(upTextColor, textOpacity200x800),
     size=markerShapeSize)

plotshape(
     series=isVisible200x800Down, 
     text='200x800',
     title='200x800Down', 
     style=markerCrossDownPlotStyle, 
     location=markerCrossDownPlotLocation, 
     color=color.new(markerCrossDownColor, shapeOpacity200x800),
     textcolor=color.new(downTextColor, textOpacity200x800),
     size=markerShapeSize)


// =====================================
// MARKERS USING LABEL
// =====================================

// LABEL VARIABLES
// markerCrossUpLabelStyle = input(label.style_arrowup, 'Label Style Up', options=[label.style_none, label.style_label_up, label.style_label_upper_right, label.style_label_right, label.style_label_lower_right, label.style_label_down, label.style_label_lower_left, label.style_label_left, label.style_label_upper_left, label.style_label_center, label.style_triangleup, label.style_triangledown, label.style_arrowup, label.style_arrowdown, label.style_xcross, label.style_cross, label.style_flag, label.style_circle], group=groupMarkers)
// markerCrossDownLabelStyle = input(label.style_arrowdown, 'Label Style Down', options=[label.style_none, label.style_label_up, label.style_label_upper_right, label.style_label_right, label.style_label_lower_right, label.style_label_down, label.style_label_lower_left, label.style_label_left, label.style_label_upper_left, label.style_label_center, label.style_triangleup, label.style_triangledown, label.style_arrowup, label.style_arrowdown, label.style_xcross, label.style_cross, label.style_flag, label.style_circle], group=groupMarkers)
// markerCrossUpLabelLocation = input(yloc.belowbar, 'Label Location Up', options=[yloc.price, yloc.abovebar, yloc.belowbar], group=groupMarkers)
// markerCrossDownLabelLocation = input(yloc.abovebar, 'Label Location Down', options=[yloc.price, yloc.abovebar, yloc.belowbar], group=groupMarkers)
// markerLabelSize = input(size.normal, 'Label Size', options=[size.auto, size.tiny, size.small, size.normal, size.large, size.huge], group=groupMarkers)

// _drawEmaCrossMarkers(emaOne, emaTwo, labelText, markerActive) => 
//     [showUpMarker, showDownMarker] = _getEmaCrossMarkerVisibility(emaOne, emaTwo, markerActive)

//     label.new(
//          showUpMarker ? bar_index : na, 
//          showUpMarker ? high : na, 
//          labelText, 
//          xloc.bar_index,
//          markerCrossUpLabelLocation,
//          markerCrossUpColor,
//          markerCrossUpLabelStyle,
//          upTextColor,
//          markerLabelSize,
//          text.align_center,
//          tooltip=labelText + ' Crossed Up')

//     label.new(
//          showDownMarker ? bar_index : na, 
//          showDownMarker ? low : na, 
//          labelText, 
//          xloc.bar_index,
//          markerCrossDownLabelLocation,
//          markerCrossDownColor,
//          markerCrossDownLabelStyle,
//          downTextColor,
//          markerLabelSize,
//          text.align_center,
//          tooltip=labelText + 'Crossed Down')

// _drawEmaCrossMarkers(ema5, ema13, '5x13', marker5x13Active)
// _drawEmaCrossMarkers(ema5, ema50, '5x50', marker5x50Active)
// _drawEmaCrossMarkers(ema13, ema50, '13x50', marker13x50Active)
// _drawEmaCrossMarkers(ema13, ema200, '13x200', marker13x200Active)
// _drawEmaCrossMarkers(ema50, ema200, '50x200', marker50x200Active)
// _drawEmaCrossMarkers(ema50, ema800, '50x800', marker50x800Active)
// _drawEmaCrossMarkers(ema200, ema800, '200x800', marker200x800Active)