// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © PriceCatch
//@version=4
study("ATR Value on Chart", shorttitle = 'ATR Value on Chart',overlay=true)

//Plot ATR for placing stop loss
length = input(14, title="ATR Period", minval=1)
smoothing = input(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])
atrmultiplier = input(title="ATR Multiplier", type=input.float, defval=0.5, minval=.01, maxval=100, step=0.05)

ma_function(source, length) =>
	if smoothing == "RMA"
		rma(source, length)
	else
		if smoothing == "SMA"
			sma(source, length)
		else
			if smoothing == "EMA"
				ema(source, length)
			else
				wma(source, length)


catr = ma_function(tr(true), length)
atrVal = (catr * atrmultiplier)


tblPos = input(title="Position on Chart", defval="Top Right", options=["Top Left", "Top Right", "Bottom Left", "Bottom Right", "Middle Left", "Middle Right" ])
tblposition = tblPos == "Top Left" ? position.top_left : tblPos == "Top Right" ? position.top_right : tblPos == "Bottom Left" ? position.bottom_left : tblPos == "Bottom Right" ? position.bottom_right : tblPos == "Middle Left" ? position.middle_left : position.middle_right

tblBorderColor = input(title="Border Color", type=input.color, defval=#636363)
celllBgColor = input(title="Background Color", type=input.color, defval=#ffffff)
cellTextColor = input(title="Text Color", type=input.color, defval=#000000)

var resultsTable = table.new(position = tblposition, columns = 1, rows = 1, bgcolor = #ffffff, border_width = 1,frame_color = tblBorderColor, frame_width = 4)
table.clear(resultsTable, 0, 0)
table.cell(resultsTable, column=0, row=0, text="ATR Value:"+tostring(atrVal,"######.000000"), text_color=cellTextColor, text_halign=text.align_right, text_valign=text.align_center, bgcolor=celllBgColor)

