
//@version=4

study("MJ - Range Plots", overlay=true)

int MS_PER_MINUTE = 1000 * 60
int MS_PER_HOUR = MS_PER_MINUTE * 60
int MS_PER_DAY = MS_PER_HOUR * 24
int MS_PER_WEEK = MS_PER_DAY * 7

numWeeksToShow = input(1, 'Num Weeks to Show')

_isWithinVerticalHourLineLookbackPeriod() =>
    lookbackTimeInMs = MS_PER_DAY * numWeeksToShow * 7
    currentBarTime = time(timeframe.period)
    currentBarTime > (timenow - lookbackTimeInMs)

isWithinLookBack = _isWithinVerticalHourLineLookbackPeriod()

/////////////////////////////////////////////////////
//
// --- MONTH ---
//
/////////////////////////////////////////////////////

inlineMonthMain = 'monthMain'
inlineMonthMid = 'monthMid'
inlineMonthHL = 'monthHL'
groupMonth = '--- Month ---'

// main
plotMonthRangeActive = input(true, 'Month HL', inline=inlineMonthMain)
monthColor = input(color.new(#311b92, 0), 'Month Color', group=groupMonth, inline=inlineMonthMain)

// HL
monthRangePlotLineWidth = input(2, 'HL Line W', options=[1,2,3,4], group=groupMonth, inline=inlineMonthHL)
monthRangePlotStyle = input(plot.style_linebr, 'HL Style', options=[plot.style_circles, plot.style_cross, plot.style_linebr, plot.style_stepline], group=groupMonth, inline=inlineMonthHL)

// mid
monthMidPlotLineWidth = input(1, 'Mid Line W', options=[1,2,3,4], group=groupMonth, inline=inlineMonthMid)
monthMidPlotStyle = input(plot.style_linebr, 'Mid Style', options=[plot.style_circles, plot.style_cross, plot.style_linebr, plot.style_stepline], group=groupMonth, inline=inlineMonthMid)
monthMidOpacity = input(0, 'Opacity', step=1, minval=0, maxval=100, group=groupMonth, inline=inlineMonthMid)

[monthHigh, monthLow, monthOpen] = security(syminfo.tickerid, 'M', [high, low, open], lookahead=true)
monthMid = (monthHigh + monthLow) / 2

isFirstBarOfMonth = monthHigh != monthHigh[1]

monthRangeHighPlot = plot(
  plotMonthRangeActive and isWithinLookBack and not isFirstBarOfMonth ? monthHigh : na,
  "Month High",
  plotMonthRangeActive ? monthColor : na,
  monthRangePlotLineWidth,
  monthRangePlotStyle
  )

monthRangeLowPlot = plot(
  plotMonthRangeActive and isWithinLookBack and not isFirstBarOfMonth ? monthLow : na,
  "Month Low",
  plotMonthRangeActive ? monthColor : na,
  monthRangePlotLineWidth,
  monthRangePlotStyle
  )

monthMidPlot = plot(
  plotMonthRangeActive and isWithinLookBack and not isFirstBarOfMonth ? monthMid : na,
  "Month Mid",
  plotMonthRangeActive ? color.new(monthColor, monthMidOpacity) : na,
  monthMidPlotLineWidth,
  monthMidPlotStyle
  )

/////////////////////////////////////////////////////
//
// --- WEEK ---
//
/////////////////////////////////////////////////////

groupWeek = '--- Week ---'
inlineWeekMain = 'weekMain'
inlineWeekMid = 'weekMid'
inlineWeekHL = 'weekHL'

// main
plotWeekRangeActive = input(true, 'Week', group=groupWeek, inline=inlineWeekMain)
weekColor = input(color.new(#089981, 10), 'Week Color', group=groupWeek, inline=inlineWeekMain)

// HL
weekRangePlotLineWidth = input(2, 'HL Line W', options=[1,2,3,4], group=groupWeek, inline=inlineWeekHL)
weekRangePlotStyle = input(plot.style_linebr, 'HL Style', options=[plot.style_circles, plot.style_cross, plot.style_linebr, plot.style_stepline], group=groupWeek, inline=inlineWeekHL)

// mid
weekMidPlotLineWidth = input(1, 'Mid Line W', options=[1,2,3,4], group=groupWeek, inline=inlineWeekMid)
weekMidPlotStyle = input(plot.style_linebr, 'Mid Style', options=[plot.style_circles, plot.style_cross, plot.style_linebr, plot.style_stepline], group=groupWeek, inline=inlineWeekMid)
weekMidOpacity = input(10, 'Week Mid Line Opacity', step=1, minval=0, maxval=100, group=groupWeek, inline=inlineWeekMid)

[weekHigh, weekLow, weekOpen] = security(syminfo.tickerid, 'W', [high, low, open], lookahead=true)
weekMid = (weekHigh + weekLow) / 2

isFirstBarOfWeek = weekHigh != weekHigh[1]

weekRangeHighPlot = plot(
  plotWeekRangeActive and isWithinLookBack and not isFirstBarOfWeek ? weekHigh : na,
  "Week High",
  plotWeekRangeActive ? weekColor : na,
  weekRangePlotLineWidth,
  weekRangePlotStyle
  )

weekRangeLowPlot = plot(
  plotWeekRangeActive and isWithinLookBack and not isFirstBarOfWeek ? weekLow : na,
  "Week Low",
  plotWeekRangeActive ? weekColor : na,
  weekRangePlotLineWidth,
  weekRangePlotStyle
  )

weekMidPlot = plot(
  plotWeekRangeActive and isWithinLookBack and not isFirstBarOfWeek ? weekMid : na,
  "Week Mid",
  plotWeekRangeActive ? color.new(weekColor, weekMidOpacity) : na,
  weekMidPlotLineWidth,
  weekMidPlotStyle
  )


