//@version=1

study("MJ - PVSRA", overlay=true, precision=0, scale=scale.none)

//////////////////////////////////////////////////
// 
// === INFO ===
// 
//////////////////////////////////////////////////

// PVSRA
// From MT4 source:

//   Situation "Climax"
//   Bars with volume >= 200% of the average volume of the 10 previous chart TFs, and bars
//   where the product of candle spread x candle volume is >= the highest for the 10 previous
//   chart time TFs.
//   Default Colors:  Bull bars are green and bear bars are red.

//   Situation "Volume Rising Above Average"
//   Bars with volume >= 150% of the average volume of the 10 previous chart TFs.
//   Default Colors:  Bull bars are blue and bear are blue-violet.

// We want to be able to override where we get the volume data for the candles.

//////////////////////////////////////////////////
// 
// === INPUTS ===
// 
//////////////////////////////////////////////////

climaxVolBullColor = input(color.lime, 'Climax Bull Color')
climaxVolBearColor = input(color.red, 'Climax Bear Color')
aboveAvgVolBullColor = input(color.blue, 'Above Average Volume Bull Color')
aboveAvgVolBearColor = input(color.fuchsia, 'Above Average Volume Bear Color')
standardVolBullColor = input(#999999, 'Standard Volume Bull Color')
standardVolBearColor = input(#4d4d4d, 'Standard Volume Bear Color')

_getBarColor(volWeight, _open, _close) => 
    if _close > _open
        volWeight == 1 
          ? climaxVolBullColor 
          : volWeight == 2 
              ? aboveAvgVolBullColor 
              : standardVolBullColor
    else
        volWeight == 1 
          ? climaxVolBearColor 
          : volWeight == 2 
              ? aboveAvgVolBearColor 
              : standardVolBearColor

//////////////////////////////////////////////////
// 
// === CALCULATIONS ===
// 
//////////////////////////////////////////////////

_vol = volume
_high = high
_low = low
_open = open
_close = close

// The math below matches MT4 PVSRA indicator source
avgVol = sum(_vol, 10) / 10 // average volume from last 10 candles
climaxVolPrevCandle = _vol * (_high - _low) //climax volume on the previous candle
highestClimaxVolPrev10 = highest(climaxVolPrevCandle, 10) // highest climax volume of the last 10 candles

isClimaxVolume = _vol >= (avgVol * 2) or climaxVolPrevCandle >= highestClimaxVolPrev10
isAboveAvgVolume = _vol >= avgVol * 1.5 and not isClimaxVolume
volWeight = isClimaxVolume ? 1 : isAboveAvgVolume ? 2 : 0

barColor = _getBarColor(volWeight, _open, _close)

barcolor(barColor) 